global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using System.Text.Json.Serialization;
global using Pulsar.BuildingBlocks.EventBus.Events;
global using Pulsar.Services.Estabelecimentos.Contracts.Enumerations;
global using Pulsar.Services.Shared;